#!/bin/bash
function print_centered { # function by trinitycoder
     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$filler" "$1" "$filler"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     #printf "\n"

     return 0
}

function clockprint
{
    date | awk '{print $4}'| cut -c1-5 | sed 's/:/ : /g' | figlet -f big && print_centered "`date | cut -c1-11`" && tput cup 0 0 && sleep 01
}

seed=0
clear
tput cup 0 0
while true; do 
clockprint | lolcat -S $seed -F 0.2
seed=$(( seed % 63 ))
seed=$(( seed + 1 ))
done;
