#
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
# ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
#

$wallpapers = ~/Imagens/wallpapers
# $image = mountain-abstract-digital-art-8k.jpg
# $image = retowave2k.jpg
$image = japanese_woman_2.png
# $image = cyberpunk-urban-scenery.jpg
# $image = LoTR-purple-1366x768.png

preload = $wallpapers/$image
# wallpaper = LVDS1, $wallpapers/mountain-abstract-digital-art-8k.jpg
wallpaper {
  monitor = eDP-1
  path = $wallpapers/$image
  fit_mode = cover # Options: cover, contain, fill, tile
}
# wallpaper = HDMI-A-1, $wallpapers/$image
wallpaper {
  monitor = HDMI-A-1
  path = $wallpapers/$image
  fit_mode = cover # Options: cover, contain, fill, tile
}

splash = false
