#! /bin/sh

BORDER_WIDTH=1

export BORDER_WIDTH

####################################################
#                                                   #
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗    #
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║    #
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║    #
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║    #
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║    #
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝    #
#####################################################

# export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
# dbus-launch bspwm-session
# exec dbus-launch --exit-with-session bspwm

sxhkd &
# pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor eDP -d 1 2 3 4 5
# bspc monitor HDMI1 -d 5 6 7 8 9
# bspc monitor -d I II III IV V VI VII VIII IX X

# checa se existem dois monitores definidos
MON=$(xrandr --listmonitors | grep Monitors | cut -b 11-)

# caso tenha, executa o setup para dois
if [ "$MON" -eq 2 ]; then
    xrandr --output eDP --primary --left-of eDP --auto &
    bspc monitor eDP -d 1 2 3 4 5
    bspc monitor HDMI -d 6 7 8 9
else
    bspc monitor eDP -d 1 2 3 4 5
fi


########## Window Settings ##############
bspc config border_width         $BORDER_WIDTH
bspc config window_gap           6 #8 #10
bspc config focus_follows_pointer	true

bspc config split_ratio          0.50
# bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true

########## Border Colors #################
# bspc config focused_border_color "#2E3440"
# bspc config normal_border_color "#2E3440"

### Dracula Theme ###
# bspc wm -r
bspc config presel_feedback_color "#6272a4"
bspc config normal_border_color "#44475a"

# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#ff79c6"
#--Cyan
bspc config active_border_color "#6272a4"
# bspc config active_border_color "#62AEEF" # Borda Azul
bspc config focused_border_color "#B542FF" # Borda Pink
# bspc config focused_border_color "#62AEEF" # Borda Azul
# bspc config focused_border_color "#8be9fd"


######### Program settings ################
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
# bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Firefox
bspc rule -a Google-chrome
bspc rule -a Thunar
# bspc rule -a Java desktop='^3' state=floating
bspc rule -a Eclipse desktop='^3' state=floating follow=on # center=on
bspc rule -a mpv state=floating focus=on
bspc rule -a vlc state=floating focus=on

######### Other Settings ################
xsetroot -cursor_name left_ptr &
xbacklight -set 50 &
redshift &

######## MY picom :) ###################
# picom  &
# picom -b --experimental-backends
picom -b

######## To set a wallpaper ####
# nitrogen --restore &
~/.fehbg

######### My Bar ###############
# polybar main
# ~/.config/polybar/switch_theme.sh tempest &
# ~/.config/polybar/switch_theme.sh tempest_rc &
~/.config/polybar/launch.sh &

# variável guarda a quantidade de monitores
# MONS=$(polybar --list-monitors | wc -l)
    # caso tenha dois, execute as duas barras
    # A bar1 é a barra com mais informações. Ela irá para o monitor
    # externo (HDMI1) caso ele esteja conectado.
# if [[ "$MONS" == "2" ]] ; then
#     MON1=HDMI1 polybar --reload bar2 &
#     MON2=eDP1 polybar --reload bar1 &
# else
#     MON1=eDP1 polybar --reload bar1 &
# fi
######## Dunst #############
# dunst ~/.config/dunst/dunstrc &

if [ -f /usr/lib/polkit-kde-authentication-agent-1 ] ; then
    /usr/lib/polkit-kde-authentication-agent-1 &
fi
