import = [
  "~/.config/alacritty/themes/breeze.toml",
  # - ~/.config/alacritty/themes/catppuccin-mocha.toml
  # - ~/.config/alacritty/themes/catppuccin-macchiato.toml
  # - ~/.config/alacritty/themes/catppuccin-latte.toml
  # - ~/.config/alacritty/themes/tokyo-night.toml
  # "~/.config/alacritty/themes/tokyo-night-storm.toml"
]

shell = { program = '/bin/zsh' }

[env]
# TERM variable
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
TERM = "xterm-256color"

[colors.primary]
# background = "0x000819"
background = "0x020221"

[scrolling]
history = 5000
multiplier = 3

# Window dimensions (changes require restart)
#
# Number of lines/columns (not pixels) in the terminal. The number of columns
# must be at least `2`, while using a value of `0` for columns and lines will
# fall back to the window manager's recommended size.
[window]
padding = { x = 5, y = 5 }

# Spread additional padding evenly around the terminal content.
dynamic_padding = false

# Window title
title = "Alacritty"

# Window class (Linux/BSD only):
class = { instance = "Alacritty", general = "Alacritty" }

dimensions = { columns = 110, lines = 28 }

# opacity = 0.5
opacity = 0.7

# Allow terminal applications to change Alacritty's window title.
dynamic_title = true

# GTK theme variant (Linux/BSD only)
#
# Override the variant of the GTK theme. Commonly supported values are `dark`
# and `light`. Set this to `None` to use the default theme variant.
#gtk_theme_variant: None

[font]
# normal = { family = 'Maple Mono', style = 'Regular' }
normal = { family = 'JetBrains Mono Nerd Font', style = 'Regular' }
bold = { family = 'JetBrains Mono Nerd Font', style = 'Bold' }
italic = { family = 'JetBrains Mono Nerd Font', style = 'MediumItalic' }
bold_italic = { family = 'JetBrains Mono Nerd Font', style = 'BoldItalic' }
size = 9
# draw_bold_text_with_bright_colors: true

[cursor]
# Cursor style
# Cursor shape
#
# Values for `shape`:
#   - ▇ Block
#   - _ Underline
#   - | Beam
# Cursor blinking state
#
# Values for `blinking`:
#   - Never: Prevent the cursor from ever blinking
#   - Off: Disable blinking by default
#   - On: Enable blinking by default
#   - Always: Force the cursor to always blink
style = { shape = 'Underline', blinking = 'On' }

#vi_mode_style: None
vi_mode_style = { shape = 'Block', blinking = 'On' }

# Cursor blinking interval in milliseconds.
#blink_interval = 750

# Time after which cursor stops blinking, in seconds.
#
# Specifying '0' will disable timeout for blinking.
#blink_timeout = 5

[selection]
save_to_clipboard = true

[keyboard]
bindings = [{ key = 'Return', mods = 'Super', action = 'SpawnNewInstance' }]
