#!/bin/bash

RED='\033[0;31m'
LBLUE='\033[1;34m'
YELLOW='\033[0;33m'
PURPLE='\033[0;36m'
ORANGE='\033[0;35m'
NC='\033[0m'

function print_centered { # function by trinitycoder
     [[ $# == 0 ]] && return 1

     declare -i TERM_COLS="$(tput cols)"
     declare -i str_len="${#1}"
     [[ $str_len -ge $TERM_COLS ]] && {
          echo "$1";
          return 0;
     }

     declare -i filler_len="$(( (TERM_COLS - str_len) / 2 ))"
     [[ $# -ge 2 ]] && ch="${2:0:1}" || ch=" "
     filler=""
     for (( i = 0; i < filler_len; i++ )); do
          filler="${filler}${ch}"
     done

     printf "%s%s%s" "$filler" "$1" "$filler"
     [[ $(( (TERM_COLS - str_len) % 2 )) -ne 0 ]] && printf "%s" "${ch}"
     printf "\n"

     return 0
} 

function pcentered {
    [[ $# -ne 2 ]] && return 1
    COLS=`tput cols`
    strlen="${#1}"
    [[ $strlen -ge $COLS ]] && {
          echo "$1";
          return 0;
     }
    [[ $strlen -eq $COLS ]] && {
        echo "$1"
        return 0
    }
    filler=0
    [[ $(( (COLS - strlen) % 2 )) -eq 0 ]] && filler=$(( (COLS - strlen) / 2 )) || filler=$(( (COLS - strlen + 1) / 2 ))
    for ((i = 0; $i < filler; i++)); do
        printf " "
    done;
    printf "$2\n"
}
pcentered "testyoooo" "${RED}testyoooo${NC}"
exit
